// opcodes.c -- the virtual cpu instruction jump array
// Copyright (C) 2012 Chris J. Baird <cjb@brushtail.apana.org.au>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>

// derived from unlicenced/BSD-2clause code by Charlie Somerville
// https://github.com/charliesome/6502


#include "opcodes.h"
#include "addressing_modes.h"
#include "instructions.h"

void* opcodes[] = {
  /*00*/ OP(brk, imm8),		/* I assume it's because of the NMOS cpu bug? */
  /*01*/ OP(ora, indx_deref),
  /*02*/ ILLEGAL,
  /*03*/ ILLEGAL,
  /*04*/ ILLEGAL,
  /*05*/ OP(ora, zp_deref),
  /*06*/ OP(asl, zp),
  /*07*/ ILLEGAL,
  /*08*/ OP(php, implied),
  /*09*/ OP(ora, imm8),
  /*0A*/ OP(asl_a, implied),
  /*0B*/ ILLEGAL,
  /*0C*/ ILLEGAL,
  /*0D*/ OP(ora, abs_deref),
  /*0E*/ OP(asl, abs),
  /*0F*/ ILLEGAL,
  /*10*/ OP(bpl, relative),
  /*11*/ OP(ora, indy_deref),
  /*12*/ ILLEGAL,
  /*13*/ ILLEGAL,
  /*14*/ ILLEGAL,
  /*15*/ OP(ora, zpx_deref),
  /*16*/ OP(asl, zpx),
  /*17*/ ILLEGAL,
  /*18*/ OP(clc, implied),
  /*19*/ OP(ora, absy_deref),
  /*1A*/ ILLEGAL,
  /*1B*/ ILLEGAL,
  /*1C*/ ILLEGAL,
  /*1D*/ OP(ora, absx_deref),
  /*1E*/ OP(asl, absx),
  /*1F*/ ILLEGAL,
  /*20*/ OP(jsr, abs),
  /*21*/ OP(and, indx_deref),
  /*22*/ ILLEGAL,
  /*23*/ ILLEGAL,
  /*24*/ OP(bit, zp_deref),
  /*25*/ OP(and, zp_deref),
  /*26*/ OP(rol, zp),
  /*27*/ ILLEGAL,
  /*28*/ OP(plp, implied),
  /*29*/ OP(and, imm8),
  /*2A*/ OP(rol_a, implied),
  /*2B*/ ILLEGAL,
  /*2C*/ OP(bit, abs_deref),
  /*2D*/ OP(and, abs_deref),
  /*2E*/ OP(rol, abs),
  /*2F*/ ILLEGAL,
  /*30*/ OP(bmi, relative),
  /*31*/ OP(and, indy_deref),
  /*32*/ ILLEGAL,
  /*33*/ ILLEGAL,
  /*34*/ ILLEGAL,
  /*35*/ OP(and, zpx_deref),
  /*36*/ OP(rol, zpx),
  /*37*/ ILLEGAL,
  /*38*/ OP(sec, implied),
  /*39*/ OP(and, absy_deref),
  /*3A*/ ILLEGAL,
  /*3B*/ ILLEGAL,
  /*3C*/ ILLEGAL,
  /*3D*/ OP(and, absx_deref),
  /*3E*/ OP(rol, absx),
  /*3F*/ ILLEGAL,
  /*40*/ OP(rti, implied),
  /*41*/ OP(eor, indx_deref),
  /*42*/ ILLEGAL,
  /*43*/ ILLEGAL,
  /*44*/ ILLEGAL,
  /*45*/ OP(eor, zp_deref),
  /*46*/ OP(lsr, zp),
  /*47*/ ILLEGAL,
  /*48*/ OP(pha, implied),
  /*49*/ OP(eor, imm8),
  /*4A*/ OP(lsr_a, implied),
  /*4B*/ ILLEGAL,
  /*4C*/ OP(jmp, imm16),
  /*4D*/ OP(eor, abs_deref),
  /*4E*/ OP(lsr, abs),
  /*4F*/ ILLEGAL,
  /*50*/ OP(bvc, relative),
  /*51*/ OP(eor, indy_deref),
  /*52*/ ILLEGAL,
  /*53*/ ILLEGAL,
  /*54*/ ILLEGAL,
  /*55*/ OP(eor, zpx_deref),
  /*56*/ OP(lsr, zpx),
  /*57*/ ILLEGAL,
  /*58*/ OP(cli, implied),
  /*59*/ OP(eor, absy_deref),
  /*5A*/ ILLEGAL,
  /*5B*/ ILLEGAL,
  /*5C*/ ILLEGAL,
  /*5D*/ OP(eor, absx_deref),
  /*5E*/ OP(lsr, absx),
  /*5F*/ ILLEGAL,
  /*60*/ OP(rts, implied),
  /*61*/ OP(adc, indx_deref),
  /*62*/ ILLEGAL,
  /*63*/ ILLEGAL,
  /*64*/ ILLEGAL,
  /*65*/ OP(adc, zp_deref),
  /*66*/ OP(ror, zp),
  /*67*/ ILLEGAL,
  /*68*/ OP(pla, implied),
  /*69*/ OP(adc, imm8),
  /*6A*/ OP(ror_a, implied),
  /*6B*/ ILLEGAL,
  /*6C*/ OP(jmp, indirect),
  /*6D*/ OP(adc, abs_deref),
  /*6E*/ OP(ror, abs),
  /*6F*/ ILLEGAL,
  /*70*/ OP(bvs, relative),
  /*71*/ OP(adc, indy_deref),
  /*72*/ ILLEGAL,
  /*73*/ ILLEGAL,
  /*74*/ ILLEGAL,
  /*75*/ OP(adc, zpx_deref),
  /*76*/ OP(ror, zpx),
  /*77*/ ILLEGAL,
  /*78*/ OP(sei, implied),
  /*79*/ OP(adc, absy_deref),
  /*7A*/ ILLEGAL,
  /*7B*/ ILLEGAL,
  /*7C*/ ILLEGAL,
  /*7D*/ OP(adc, absx_deref),
  /*7E*/ OP(ror, absx),
  /*7F*/ ILLEGAL,
  /*80*/ ILLEGAL,
  /*81*/ OP(sta, indx),
  /*82*/ ILLEGAL,
  /*83*/ ILLEGAL,
  /*84*/ OP(sty, zp),
  /*85*/ OP(sta, zp),
  /*86*/ OP(stx, zp),
  /*87*/ ILLEGAL,
  /*88*/ OP(dey, implied),
  /*89*/ ILLEGAL,
  /*8A*/ OP(txa, implied),
  /*8B*/ ILLEGAL,
  /*8C*/ OP(sty, abs),
  /*8D*/ OP(sta, abs),
  /*8E*/ OP(stx, abs),
  /*8F*/ ILLEGAL,
  /*90*/ OP(bcc, relative),
  /*91*/ OP(sta, indy),
  /*92*/ ILLEGAL,
  /*93*/ ILLEGAL,
  /*94*/ OP(sty, zpx),
  /*95*/ OP(sta, zpx),
  /*96*/ OP(stx, zpy),
  /*97*/ ILLEGAL,
  /*98*/ OP(tya, implied),
  /*99*/ OP(sta, absy),
  /*9A*/ OP(txs, implied),
  /*9B*/ ILLEGAL,
  /*9C*/ ILLEGAL,
  /*9D*/ OP(sta, absx),
  /*9E*/ ILLEGAL,
  /*9F*/ ILLEGAL,
  /*A0*/ OP(ldy, imm8),
  /*A1*/ OP(lda, indx_deref),
  /*A2*/ OP(ldx, imm8),
  /*A3*/ ILLEGAL,
  /*A4*/ OP(ldy, zp_deref),
  /*A5*/ OP(lda, zp_deref),
  /*A6*/ OP(ldx, zp_deref),
  /*A7*/ ILLEGAL,
  /*A8*/ OP(tay, implied),
  /*A9*/ OP(lda, imm8),
  /*AA*/ OP(tax, implied),
  /*AB*/ ILLEGAL,
  /*AC*/ OP(ldy, abs_deref),
  /*AD*/ OP(lda, abs_deref),
  /*AE*/ OP(ldx, abs_deref),
  /*AF*/ ILLEGAL,
  /*B0*/ OP(bcs, relative),
  /*B1*/ OP(lda, indy_deref),
  /*B2*/ ILLEGAL,
  /*B3*/ ILLEGAL,
  /*B4*/ OP(ldy, zpx_deref),
  /*B5*/ OP(lda, zpx_deref),
  /*B6*/ OP(ldx, zpy_deref),
  /*B7*/ ILLEGAL,
  /*B8*/ OP(clv, implied),
  /*B9*/ OP(lda, absy_deref),
  /*BA*/ OP(tsx, implied),
  /*BB*/ ILLEGAL,
  /*BC*/ OP(ldy, absx_deref),
  /*BD*/ OP(lda, absx_deref),
  /*BE*/ OP(ldx, absy_deref),
  /*BF*/ ILLEGAL,
  /*C0*/ OP(cpy, imm8),
  /*C1*/ OP(cmp, indx_deref),
  /*C2*/ ILLEGAL,
  /*C3*/ ILLEGAL,
  /*C4*/ OP(cpy, zp_deref),
  /*C5*/ OP(cmp, zp_deref),
  /*C6*/ OP(dec, zp),
  /*C7*/ ILLEGAL,
  /*C8*/ OP(iny, implied),
  /*C9*/ OP(cmp, imm8),
  /*CA*/ OP(dex, implied),
  /*CB*/ ILLEGAL,
  /*CC*/ OP(cpy, abs_deref),
  /*CD*/ OP(cmp, abs_deref),
  /*CE*/ OP(dec, abs),
  /*CF*/ ILLEGAL,
  /*D0*/ OP(bne, relative),
  /*D1*/ OP(cmp, indy_deref),
  /*D2*/ ILLEGAL,
  /*D3*/ ILLEGAL,
  /*D4*/ ILLEGAL,
  /*D5*/ OP(cmp, zpx_deref),
  /*D6*/ OP(dec, zpx),
  /*D7*/ ILLEGAL,
  /*D8*/ OP(cld, implied),
  /*D9*/ OP(cmp, absy_deref),
  /*DA*/ ILLEGAL,
  /*DB*/ ILLEGAL,
  /*DC*/ ILLEGAL,
  /*DD*/ OP(cmp, absx_deref),
  /*DE*/ OP(dec, absx),
  /*DF*/ ILLEGAL,
  /*E0*/ OP(cpx, imm8),
  /*E1*/ OP(sbc, indx_deref),
  /*E2*/ ILLEGAL,
  /*E3*/ ILLEGAL,
  /*E4*/ OP(cpx, zp_deref),
  /*E5*/ OP(sbc, zp_deref),
  /*E6*/ OP(inc, zp),
  /*E7*/ ILLEGAL,
  /*E8*/ OP(inx, implied),
  /*E9*/ OP(sbc, imm8),
  /*EA*/ OP(nop, implied),
  /*EB*/ ILLEGAL,
  /*EC*/ OP(cpx, abs_deref),
  /*ED*/ OP(sbc, abs_deref),
  /*EE*/ OP(inc, abs),
  /*EF*/ ILLEGAL,
  /*F0*/ OP(beq, relative),
  /*F1*/ OP(sbc, indy_deref),
  /*F2*/ ILLEGAL,
  /*F3*/ ILLEGAL,
  /*F4*/ ILLEGAL,
  /*F5*/ OP(sbc, zpx_deref),
  /*F6*/ OP(inc, zpx),
  /*F7*/ ILLEGAL,
  /*F8*/ OP(sed, implied),
  /*F9*/ OP(sbc, absy_deref),
  /*FA*/ ILLEGAL,
  /*FB*/ ILLEGAL,
  /*FC*/ ILLEGAL,
  /*FD*/ OP(sbc, absx_deref),
  /*FE*/ OP(inc, absx),
  /*FF*/ ILLEGAL
};
